version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./config/docker/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=sandbox

  django:
    build:
      context: .
      dockerfile: ./config/docker/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - mailhog
    environment:
      - POSTGRES_USER=sandbox
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"




  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

