# This file is autogenerated by edgy.project code generator.
# All changes will be overwritten.

import os
from setuptools import setup, find_packages

root_dir = os.path.dirname(os.path.abspath(__file__))

tolines = lambda c: list(filter(None, map(lambda s: s.strip(), c.split('\n'))))


def read(filename, flt=None):
    try:
        with open(filename) as f:
            content = f.read().strip()
            return flt(content) if callable(flt) else content
    except FileNotFoundError:
        return ''


# Py3 compatibility hacks, borrowed from IPython.
try:
    execfile
except NameError:

    def execfile(fname, globs, locs=None):
        locs = locs or globs
        exec(compile(open(fname).read(), fname, "exec"), globs, locs)


version_ns = {}
try:
    execfile(os.path.join(root_dir, 'sandbox/_version.py'), version_ns)
except FileNotFoundError:
    version = 'dev'
else:
    version = version_ns.get('__version__', 'dev')

setup(
    name='sandbox',
    description='A django sandbox',
    license='Not open source',
    install_requires=[
        'pillow==4.0.0', 'argon2-cffi==16.3.0', 'awesome-slugify==1.6.5',
        'django ==1.11rc1', 'django-allauth==0.31.0', 'django-braces==1.11.0',
        'django-crispy-forms==1.6.1', 'django-environ ==0.4.1',
        'django-model-utils==2.6.1', 'django-redis==4.7.0', 'pytz==2016.10',
        'redis>=2.10.5', 'wheel ==0.29.0', 'celery==4.0.2',
        'whitenoise ==3.3.0', 'psycopg2==2.7.1'
    ],
    version=version,
    long_description=read('README.rst'),
    classifiers=read('classifiers.txt', tolines),
    packages=find_packages(exclude=['ez_setup', 'example', 'test']),
    include_package_data=True,
    extras_require={
        'dev': [
            'Sphinx==1.5.3', 'Werkzeug==0.12.1', 'coverage==4.3.4',
            'django-coverage-plugin==1.5.0', 'django-debug-toolbar==1.6',
            'django-extensions==1.7.7', 'django-test-plus==1.0.17',
            'factory-boy==2.8.1', 'ipdb==0.10.2', 'mock >=2,<3', 'nose >=1,<2',
            'pylint >=1,<2', 'pytest >=3,<4', 'pytest-cov >=2,<3',
            'pytest-django==3.1.2', 'pytest-sugar==0.8.0',
            'pytest-timeout >=1,<2', 'sphinx_rtd_theme', 'yapf'
        ]
    },
    url='',
    download_url=''.format(version=version), )
